-- MySQL Script generated by MySQL Workbench
-- 11/05/15 11:30:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `proyecto2` ;

-- -----------------------------------------------------
-- Table `proyecto2`.`confederaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`confederaciones` (
  `idconfederaciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `icono` BLOB NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idconfederaciones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idadministrador`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `fecha_inicio` DATE NULL COMMENT '',
  `confederacion` TINYINT(1) NULL COMMENT '',
  `nacionales` TINYINT(1) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  `administrador_idadministrador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEvento`)  COMMENT '',
  INDEX `fk_Evento_administrador1_idx` (`administrador_idadministrador` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_administrador1`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `proyecto2`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Categoria_Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Categoria_Grupo` (
  `idCategoria_Grupo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idCategoria_Grupo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Evento_idEvento` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  `Categoria_Grupo_idCategoria_Grupo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idgrupo`)  COMMENT '',
  INDEX `fk_grupo_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  INDEX `fk_grupo_Categoria_Grupo1_idx` (`Categoria_Grupo_idCategoria_Grupo` ASC)  COMMENT '',
  CONSTRAINT `fk_grupo_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_Categoria_Grupo1`
    FOREIGN KEY (`Categoria_Grupo_idCategoria_Grupo`)
    REFERENCES `proyecto2`.`Categoria_Grupo` (`idCategoria_Grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Continente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Continente` (
  `idContinente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idContinente`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Pais` (
  `idPais` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `bandera` BLOB NULL COMMENT '',
  `Continente_idContinente` INT NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idPais`)  COMMENT '',
  INDEX `fk_Pais_Continente1_idx` (`Continente_idContinente` ASC)  COMMENT '',
  CONSTRAINT `fk_Pais_Continente1`
    FOREIGN KEY (`Continente_idContinente`)
    REFERENCES `proyecto2`.`Continente` (`idContinente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `bandera` BLOB NULL COMMENT '',
  `tecnico` VARCHAR(95) NULL COMMENT '',
  `confederaciones_idconfederaciones` INT NOT NULL COMMENT '',
  `grupo_idgrupo` INT NOT NULL COMMENT '',
  `Pais_idPais` INT NOT NULL COMMENT '',
  `seleccion` TINYINT(1) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idequipo`)  COMMENT '',
  INDEX `fk_equipo_confederaciones1_idx` (`confederaciones_idconfederaciones` ASC)  COMMENT '',
  INDEX `fk_equipo_grupo1_idx` (`grupo_idgrupo` ASC)  COMMENT '',
  INDEX `fk_equipo_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  CONSTRAINT `fk_equipo_confederaciones1`
    FOREIGN KEY (`confederaciones_idconfederaciones`)
    REFERENCES `proyecto2`.`confederaciones` (`idconfederaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `proyecto2`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`alineacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`alineacion` (
  `idalineacion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `equipo_idequipo` INT NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idalineacion`)  COMMENT '',
  INDEX `fk_alineacion_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  CONSTRAINT `fk_alineacion_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`posicion` (
  `idposicion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idposicion`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`jugador` (
  `idjugador` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `numeroCamiseta` INT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellidos` VARCHAR(45) NULL COMMENT '',
  `cedula` VARCHAR(45) NULL COMMENT '',
  `foto` BLOB NULL COMMENT '',
  `equipo_idequipo` INT NOT NULL COMMENT '',
  `suspendido` TINYINT(1) NULL COMMENT '',
  `alineacion_idalineacion` INT NOT NULL COMMENT '',
  `Pais_idPais` INT NOT NULL COMMENT '',
  `capitan` TINYINT(1) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  `posicion_idposicion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idjugador`)  COMMENT '',
  INDEX `fk_jugador_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  INDEX `fk_jugador_alineacion1_idx` (`alineacion_idalineacion` ASC)  COMMENT '',
  INDEX `fk_jugador_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  UNIQUE INDEX `numeroCamiseta_UNIQUE` (`numeroCamiseta` ASC)  COMMENT '',
  INDEX `fk_jugador_posicion1_idx` (`posicion_idposicion` ASC)  COMMENT '',
  CONSTRAINT `fk_jugador_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_alineacion1`
    FOREIGN KEY (`alineacion_idalineacion`)
    REFERENCES `proyecto2`.`alineacion` (`idalineacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_posicion1`
    FOREIGN KEY (`posicion_idposicion`)
    REFERENCES `proyecto2`.`posicion` (`idposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`estadio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`estadio` (
  `idestadio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Pais_idPais` INT NOT NULL COMMENT '',
  `capacidad` INT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idestadio`)  COMMENT '',
  INDEX `fk_estadio_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  CONSTRAINT `fk_estadio_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`partido` (
  `idpartido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Evento_idEvento` INT NOT NULL COMMENT '',
  `EquipoLocal` INT NOT NULL COMMENT '',
  `EquipoVisita` INT NOT NULL COMMENT '',
  `Ganador` INT NULL COMMENT '',
  `estadio_idestadio` INT NOT NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idpartido`)  COMMENT '',
  INDEX `fk_partido_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  INDEX `fk_partido_equipo1_idx` (`EquipoLocal` ASC)  COMMENT '',
  INDEX `fk_partido_equipo2_idx` (`EquipoVisita` ASC)  COMMENT '',
  INDEX `fk_partido_estadio1_idx` (`estadio_idestadio` ASC)  COMMENT '',
  CONSTRAINT `fk_partido_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_equipo1`
    FOREIGN KEY (`EquipoLocal`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_equipo2`
    FOREIGN KEY (`EquipoVisita`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_estadio1`
    FOREIGN KEY (`estadio_idestadio`)
    REFERENCES `proyecto2`.`estadio` (`idestadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`bitacora` (
  `idbitacora` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idbitacora`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`parametros` (
  `idparametros` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cantidad_equipos` INT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idparametros`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Evento_has_confederaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Evento_has_confederaciones` (
  `Evento_idEvento` INT NOT NULL COMMENT '',
  `confederaciones_idconfederaciones` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Evento_idEvento`, `confederaciones_idconfederaciones`)  COMMENT '',
  INDEX `fk_Evento_has_confederaciones_confederaciones1_idx` (`confederaciones_idconfederaciones` ASC)  COMMENT '',
  INDEX `fk_Evento_has_confederaciones_Evento_idx` (`Evento_idEvento` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_has_confederaciones_Evento`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_confederaciones_confederaciones1`
    FOREIGN KEY (`confederaciones_idconfederaciones`)
    REFERENCES `proyecto2`.`confederaciones` (`idconfederaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Evento_has_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Evento_has_equipo` (
  `Evento_idEvento` INT NOT NULL COMMENT '',
  `equipo_idequipo` INT NOT NULL COMMENT '',
  `ganador` TINYINT(1) NULL COMMENT '',
  `segundo lugar` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`Evento_idEvento`, `equipo_idequipo`)  COMMENT '',
  INDEX `fk_Evento_has_equipo_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  INDEX `fk_Evento_has_equipo_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_has_equipo_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_equipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`partido_has_jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`partido_has_jugador` (
  `partido_idpartido` INT NOT NULL COMMENT '',
  `jugador_idjugador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`partido_idpartido`, `jugador_idjugador`)  COMMENT '',
  INDEX `fk_partido_has_jugador_jugador1_idx` (`jugador_idjugador` ASC)  COMMENT '',
  INDEX `fk_partido_has_jugador_partido1_idx` (`partido_idpartido` ASC)  COMMENT '',
  CONSTRAINT `fk_partido_has_jugador_partido1`
    FOREIGN KEY (`partido_idpartido`)
    REFERENCES `proyecto2`.`partido` (`idpartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_has_jugador_jugador1`
    FOREIGN KEY (`jugador_idjugador`)
    REFERENCES `proyecto2`.`jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Catalogo_de_Acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Catalogo_de_Acciones` (
  `idCatalogo_de_Acciones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idCatalogo_de_Acciones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Accion` (
  `idAccion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `jugador_idjugador` INT NOT NULL COMMENT '',
  `partido_idpartido` INT NOT NULL COMMENT '',
  `tiempo` INT NULL COMMENT '',
  `idCatalogo_de_Acciones` INT NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idAccion`)  COMMENT '',
  INDEX `fk_Accion_jugador1_idx` (`jugador_idjugador` ASC)  COMMENT '',
  INDEX `fk_Accion_partido1_idx` (`partido_idpartido` ASC)  COMMENT '',
  INDEX `fk_Accion_Catalogo de Acciones1_idx` (`idCatalogo_de_Acciones` ASC)  COMMENT '',
  CONSTRAINT `fk_Accion_jugador1`
    FOREIGN KEY (`jugador_idjugador`)
    REFERENCES `proyecto2`.`jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accion_partido1`
    FOREIGN KEY (`partido_idpartido`)
    REFERENCES `proyecto2`.`partido` (`idpartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accion_Catalogo de Acciones1`
    FOREIGN KEY (`idCatalogo_de_Acciones`)
    REFERENCES `proyecto2`.`Catalogo_de_Acciones` (`idCatalogo_de_Acciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`bitacoraPorEquipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`bitacoraPorEquipo` (
  `idbitacoraPorEquipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pj` INT NULL COMMENT '',
  `pg` INT NULL COMMENT '',
  `pe` INT NULL COMMENT '',
  `pp` INT NULL COMMENT '',
  `GF` INT NULL COMMENT '',
  `gc` INT NULL COMMENT '',
  `grupo_idgrupo` INT NOT NULL COMMENT '',
  `equipo_idequipo` INT NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL COMMENT '',
  `Fecha_Edicion` DATE NULL COMMENT '',
  PRIMARY KEY (`idbitacoraPorEquipo`)  COMMENT '',
  INDEX `fk_bitacoraPorEquipo_grupo1_idx` (`grupo_idgrupo` ASC)  COMMENT '',
  INDEX `fk_bitacoraPorEquipo_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  CONSTRAINT `fk_bitacoraPorEquipo_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `proyecto2`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bitacoraPorEquipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto2`.`Evento_has_Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`Evento_has_Pais` (
  `Evento_idEvento` INT NOT NULL COMMENT '',
  `Pais_idPais` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Evento_idEvento`, `Pais_idPais`)  COMMENT '',
  INDEX `fk_Evento_has_Pais_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  INDEX `fk_Evento_has_Pais_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_has_Pais_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Pais_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
