/*call insert_continente('Africa');
call insert_continente('Asia');
call insert_continente('Norte,Centroamerica y Caribe');
call insert_continente('Oceania');
call insert_continente('Sudamerica');*/


call insert_categoria_grupo('First Round');
call insert_categoria_grupo('Second Round');
call insert_categoria_grupo('Round of 16');
call insert_categoria_grupo('Quarterfinals');
call insert_categoria_grupo('Semifinals');
call insert_categoria_grupo('Final');

/*catalogo_de_acciones*/
call insert_catalogo_de_acciones('Goal');
call insert_catalogo_de_acciones('Red Card');
call insert_catalogo_de_acciones('Yellow Card');
call insert_catalogo_de_acciones('Save');
call insert_catalogo_de_acciones('Offside');
call insert_catalogo_de_acciones('Corner');

/*'Posicion'*/

call insert_posicion('Goalkeeper');
call insert_posicion('Defender');
call insert_posicion('Midfielder');
call insert_posicion('Striker');

/*No estan terminados xD*/
call insertar_pais('Afganistan');
call insertar_pais('Africa del Sur');
call insertar_pais('Albania');
call insertar_pais('Alemania');
call insertar_pais('Andorra');
call insertar_pais('Angola');
call insertar_pais('Antigua y Barbuda');
call insertar_pais('Antillas Holandesas');
call insertar_pais('Arabia Saudita');
call insertar_pais('Argelia');
call insertar_pais('Argentina');
call insertar_pais('Armenia');
call insertar_pais('Aruba');
call insertar_pais('Australia');
call insertar_pais('Austria');
call insertar_pais('Azerbaijan');
call insertar_pais('Bahamas');
call insertar_pais('Bahrain');
call insertar_pais('Bangladesh');
call insertar_pais('Barbados');
call insertar_pais('Belarusia');
call insertar_pais('Belgica');
call insertar_pais('Belice');
call insertar_pais('Benin');
call insertar_pais('Bermudas');
call insertar_pais('Bolivia');
call insertar_pais('Bosnia');
call insertar_pais('Botswana');
call insertar_pais('Brasil');
call insertar_pais('Brunei Darussulam');
call insertar_pais('Bulgaria');
call insertar_pais('Burkina Faso');
call insertar_pais('Burundi');
call insertar_pais('Butan');
call insertar_pais('Camboya');
call insertar_pais('Camerun');
call insertar_pais('Canada');
call insertar_pais('Cape Verde');
call insertar_pais('Chad');
call insertar_pais('Chile');
call insertar_pais('China');
call insertar_pais('Chipre');
call insertar_pais('Colombia');
call insertar_pais('Comoros');
call insertar_pais('Congo');
call insertar_pais('Corea del Norte');
call insertar_pais('Corea del Sur');
call insertar_pais('Costa Rica');
call insertar_pais('Croasia');
call insertar_pais('Cuba');
call insertar_pais('Dinamarca');
call insertar_pais('Djibouti');
call insertar_pais('Dominica');
call insertar_pais('Ecuador');
call insertar_pais('Egipto');
call insertar_pais('El Salvador');
call insertar_pais('Emiratos Arabes Unidos');
call insertar_pais('Eritrea');
call insertar_pais('Eslovenia');
call insertar_pais('Espana');
call insertar_pais('Estados Unidos');
call insertar_pais('Estonia');
call insertar_pais('Etiopia');
call insertar_pais('Fiji');
call insertar_pais('Filipinas');
call insertar_pais('Finlandia');
call insertar_pais('Francia');
call insertar_pais('Gabon');
call insertar_pais('Gambia');
call insertar_pais('Georgia');
call insertar_pais('Ghana');
call insertar_pais('Granada');
call insertar_pais('Grecia');
call insertar_pais('Groenlandia');
call insertar_pais('Guadalupe');
call insertar_pais('Guam');
call insertar_pais('Guatemala');
call insertar_pais('Guayana Francesa');
call insertar_pais('Guerney');
call insertar_pais('Guinea');
call insertar_pais('Guinea-Bissau');
call insertar_pais('Guinea Equatorial');
call insertar_pais('Guyana');
call insertar_pais('Haiti');
call insertar_pais('Holanda');
call insertar_pais('Honduras');
call insertar_pais('Hong Kong');
call insertar_pais('Hungria');
call insertar_pais('India');
call insertar_pais('Indonesia');
call insertar_pais('Irak');
call insertar_pais('Iran');
call insertar_pais('Costa de Marfil');
call insertar_pais('Israel');
call insertar_pais('Italia');
call insertar_pais('Jamaica');
call insertar_pais('Japon');
call insertar_pais('Jersey');
call insertar_pais('Jordania');
call insertar_pais('Kazakhstan');
call insertar_pais('Kenia');
call insertar_pais('Kiribati');
call insertar_pais('Kuwait');
call insertar_pais('Kyrgyzstan');
call insertar_pais('Laos');
call insertar_pais('Latvia');
call insertar_pais('Lesotho');
call insertar_pais('Libano');
call insertar_pais('Liberia');
call insertar_pais('Libia');
call insertar_pais('Liechtenstein');
call insertar_pais('Lituania');
call insertar_pais('Luxemburgo');
call insertar_pais('Macao');
call insertar_pais('Macedonia');
call insertar_pais('Madagascar');
call insertar_pais('Malasia');
call insertar_pais('Malawi');
call insertar_pais('Maldivas');
call insertar_pais('Mali');
call insertar_pais('Malta');
call insertar_pais('Marruecos');
call insertar_pais('Martinica');
call insertar_pais('Mauricio');
call insertar_pais('Mauritania');
call insertar_pais('Mexico');
call insertar_pais('Micronesia');
call insertar_pais('Moldova');
call insertar_pais('Monaco');
call insertar_pais('Mongolia');
call insertar_pais('Mozambique');
call insertar_pais('Myanmar (Burma)');
call insertar_pais('Namibia');
call insertar_pais('Nepal');
call insertar_pais('Nicaragua');
call insertar_pais('Niger');
call insertar_pais('Nigeria');
call insertar_pais('Noruega');
call insertar_pais('Nueva Caledonia');
call insertar_pais('Nueva Zealandia');
call insertar_pais('Oman');
call insertar_pais('Pakistan');
call insertar_pais('Palestina');
call insertar_pais('Panama');
call insertar_pais('Papua Nueva Guinea');
call insertar_pais('Paraguay');
call insertar_pais('Peru');
call insertar_pais('Polinesia Francesa');
call insertar_pais('Polonia');
call insertar_pais('Portugal');
call insertar_pais('Puerto Rico');
call insertar_pais('Qatar');
call insertar_pais('Reino Unido');
call insertar_pais('Republica Centroafricana');
call insertar_pais('Republica Checa');
call insertar_pais('Republica Democratica del Congo');
call insertar_pais('Republica Dominicana');
call insertar_pais('Republica Eslovaca');
call insertar_pais('Reunion');
call insertar_pais('Ruanda');
call insertar_pais('Rumania');
call insertar_pais('Rusia');
call insertar_pais('Sahara');
call insertar_pais('Samoa');
call insertar_pais('San Cristobal-Nevis (St. Kitts)');
call insertar_pais('San Marino');
call insertar_pais('San Vincente y las Granadinas');
call insertar_pais('Santa Helena');
call insertar_pais('Santa Lucia');
call insertar_pais('Santa Sede (Vaticano)');
call insertar_pais('Sao Tome & Principe');
call insertar_pais('Senegal');
call insertar_pais('Seychelles');
call insertar_pais('Sierra Leona');
call insertar_pais('Singapur');
call insertar_pais('Siria');
call insertar_pais('Somalia');
call insertar_pais('Sri Lanka (Ceilan)');
call insertar_pais('Sudan');
call insertar_pais('Sudan del Sur');
call insertar_pais('Suecia');
call insertar_pais('Suiza');
call insertar_pais('Sur Africa');
call insertar_pais('Surinam');
call insertar_pais('Swaziland');
call insertar_pais('Tailandia');
call insertar_pais('Taiwan');
call insertar_pais('Tajikistan');
call insertar_pais('Tanzania');
call insertar_pais('Timor Oriental');
call insertar_pais('Togo');
call insertar_pais('Tokelau');
call insertar_pais('Tonga');
call insertar_pais('Trinidad & Tobago');
call insertar_pais('Tunisia');
call insertar_pais('Turkmenistan');
call insertar_pais('Turquia');
call insertar_pais('Ucrania');
call insertar_pais('Uganda');
call insertar_pais('Union Europea');
call insertar_pais('Uruguay');
call insertar_pais('Uzbekistan');
call insertar_pais('Vanuatu');
call insertar_pais('Venezuela');
call insertar_pais('Vietnam');
call insertar_pais('Yemen');
call insertar_pais('Zambia');
call insertar_pais('Zimbabwe');