-- MySQL Script generated by MySQL Workbench
-- 11/09/15 22:50:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto2` DEFAULT CHARACTER SET utf8 ;
USE `proyecto2` ;

-- -----------------------------------------------------
-- Table `proyecto2`.`catalogo_de_acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`catalogo_de_acciones` (
  `idCatalogo_de_Acciones` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idCatalogo_de_Acciones`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`continente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`continente` (
  `idContinente` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idContinente`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`pais` (
  `idPais` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bandera` BLOB NULL DEFAULT NULL COMMENT '',
  `Continente_idContinente` INT(11) NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idPais`)  COMMENT '',
  INDEX `fk_Pais_Continente1_idx` (`Continente_idContinente` ASC)  COMMENT '',
  CONSTRAINT `fk_Pais_Continente1`
    FOREIGN KEY (`Continente_idContinente`)
    REFERENCES `proyecto2`.`continente` (`idContinente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`confederaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`confederaciones` (
  `idconfederaciones` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `icono` BLOB NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idconfederaciones`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`equipo` (
  `idequipo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bandera` BLOB NULL DEFAULT NULL COMMENT '',
  `tecnico` VARCHAR(95) NULL DEFAULT NULL COMMENT '',
  `confederaciones_idconfederaciones` INT(11) NOT NULL COMMENT '',
  `Pais_idPais` INT(11) NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idequipo`)  COMMENT '',
  INDEX `fk_equipo_confederaciones1_idx` (`confederaciones_idconfederaciones` ASC)  COMMENT '',
  INDEX `fk_equipo_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  CONSTRAINT `fk_equipo_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_confederaciones1`
    FOREIGN KEY (`confederaciones_idconfederaciones`)
    REFERENCES `proyecto2`.`confederaciones` (`idconfederaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`alineacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`alineacion` (
  `idalineacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `equipo_idequipo` INT(11) NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idalineacion`)  COMMENT '',
  INDEX `fk_alineacion_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  CONSTRAINT `fk_alineacion_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`posicion` (
  `idposicion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idposicion`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`jugador` (
  `idjugador` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `numeroCamiseta` INT(11) NULL DEFAULT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `apellidos` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cedula` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `foto` BLOB NULL DEFAULT NULL COMMENT '',
  `equipo_idequipo` INT(11) NOT NULL COMMENT '',
  `suspendido` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `alineacion_idalineacion` INT(11) NULL DEFAULT NULL COMMENT '',
  `Pais_idPais` INT(11) NOT NULL COMMENT '',
  `capitan` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  `posicion_idposicion` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idjugador`)  COMMENT '',
  UNIQUE INDEX `numeroCamiseta_UNIQUE` (`numeroCamiseta` ASC)  COMMENT '',
  INDEX `fk_jugador_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  INDEX `fk_jugador_alineacion1_idx` (`alineacion_idalineacion` ASC)  COMMENT '',
  INDEX `fk_jugador_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  INDEX `fk_jugador_posicion1_idx` (`posicion_idposicion` ASC)  COMMENT '',
  CONSTRAINT `fk_jugador_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_alineacion1`
    FOREIGN KEY (`alineacion_idalineacion`)
    REFERENCES `proyecto2`.`alineacion` (`idalineacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_posicion1`
    FOREIGN KEY (`posicion_idposicion`)
    REFERENCES `proyecto2`.`posicion` (`idposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`tipo_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`tipo_eventos` (
  `idTipo_Eventos` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idTipo_Eventos`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`administrador` (
  `idadministrador` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `password` VARBINARY(200) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idadministrador`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`evento` (
  `idEvento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `fecha_inicio` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  `administrador_idadministrador` INT(11) NOT NULL COMMENT '',
  `cantidad_equipos` INT(11) NULL DEFAULT NULL COMMENT '',
  `Tipo_Eventos_idTipo_Eventos` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idEvento`)  COMMENT '',
  INDEX `fk_Evento_administrador1_idx` (`administrador_idadministrador` ASC)  COMMENT '',
  INDEX `fk_Evento_Tipo_Eventos1_idx` (`Tipo_Eventos_idTipo_Eventos` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_Tipo_Eventos1`
    FOREIGN KEY (`Tipo_Eventos_idTipo_Eventos`)
    REFERENCES `proyecto2`.`tipo_eventos` (`idTipo_Eventos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_administrador1`
    FOREIGN KEY (`administrador_idadministrador`)
    REFERENCES `proyecto2`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`estadio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`estadio` (
  `idestadio` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Pais_idPais` INT(11) NOT NULL COMMENT '',
  `capacidad` INT(11) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idestadio`)  COMMENT '',
  INDEX `fk_estadio_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  CONSTRAINT `fk_estadio_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`partido`
-- -----------------------------------------------------
CREATE TABLE `partido` (
  `idpartido` int(11) NOT NULL AUTO_INCREMENT,
  `Evento_idEvento` int(11) NOT NULL,
  `EquipoLocal` int(11) NOT NULL,
  `EquipoVisita` int(11) NOT NULL,
  `Ganador` int(11) DEFAULT NULL,
  `estadio_idestadio` int(11) NOT NULL,
  `fecha` datetime DEFAULT NULL,
  `Fecha_Creacion` date DEFAULT NULL,
  `Fecha_Edicion` date DEFAULT NULL,
  `grupo_idgrupo` int(11) NOT NULL,
  PRIMARY KEY (`idpartido`),
  KEY `fk_partido_Evento1_idx` (`Evento_idEvento`),
  KEY `fk_partido_equipo1_idx` (`EquipoLocal`),
  KEY `fk_partido_equipo2_idx` (`EquipoVisita`),
  KEY `fk_partido_estadio1_idx` (`estadio_idestadio`),
  KEY `fk_partido_grupo1_idx` (`grupo_idgrupo`),
  CONSTRAINT `fk_partido_Evento1` FOREIGN KEY (`Evento_idEvento`) REFERENCES `evento` (`idEvento`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_equipo1` FOREIGN KEY (`EquipoLocal`) REFERENCES `equipo` (`idequipo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_equipo2` FOREIGN KEY (`EquipoVisita`) REFERENCES `equipo` (`idequipo`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_estadio1` FOREIGN KEY (`estadio_idestadio`) REFERENCES `estadio` (`idestadio`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_partido_grupo1` FOREIGN KEY (`grupo_idgrupo`) REFERENCES `grupo` (`idgrupo`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`accion` (
  `idAccion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `jugador_idjugador` INT(11) NOT NULL COMMENT '',
  `partido_idpartido` INT(11) NOT NULL COMMENT '',
  `tiempo` INT(11) NULL DEFAULT NULL COMMENT '',
  `idCatalogo_de_Acciones` INT(11) NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  `equipo_idequipo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idAccion`)  COMMENT '',
  INDEX `fk_Accion_jugador1_idx` (`jugador_idjugador` ASC)  COMMENT '',
  INDEX `fk_Accion_partido1_idx` (`partido_idpartido` ASC)  COMMENT '',
  INDEX `fk_Accion_Catalogo de Acciones1_idx` (`idCatalogo_de_Acciones` ASC)  COMMENT '',
  INDEX `fk_Accion_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  CONSTRAINT `fk_Accion_Catalogo de Acciones1`
    FOREIGN KEY (`idCatalogo_de_Acciones`)
    REFERENCES `proyecto2`.`catalogo_de_acciones` (`idCatalogo_de_Acciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accion_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accion_jugador1`
    FOREIGN KEY (`jugador_idjugador`)
    REFERENCES `proyecto2`.`jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accion_partido1`
    FOREIGN KEY (`partido_idpartido`)
    REFERENCES `proyecto2`.`partido` (`idpartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`bitacora` (
  `idbitacora` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha_Creacion` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  `pj` INT(11) NULL DEFAULT NULL COMMENT '',
  `pg` INT(11) NULL DEFAULT NULL COMMENT '',
  `pe` INT(11) NULL DEFAULT NULL COMMENT '',
  `pp` INT(11) NULL DEFAULT NULL COMMENT '',
  `GF` INT(11) NULL DEFAULT NULL COMMENT '',
  `gc` INT(11) NULL DEFAULT NULL COMMENT '',
  `grupo_idgrupo` INT(11) NOT NULL COMMENT '',
  `equipo_idequipo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`idbitacora`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`categoria_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`categoria_grupo` (
  `idCategoria_Grupo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idCategoria_Grupo`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`grupo` (
  `idgrupo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Evento_idEvento` INT(11) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  `Categoria_Grupo_idCategoria_Grupo` INT(11) NOT NULL COMMENT '',
  `id_nextgrupo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idgrupo`)  COMMENT '',
  INDEX `fk_grupo_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  INDEX `fk_grupo_Categoria_Grupo1_idx` (`Categoria_Grupo_idCategoria_Grupo` ASC)  COMMENT '',
  CONSTRAINT `fk_grupo_Categoria_Grupo1`
    FOREIGN KEY (`Categoria_Grupo_idCategoria_Grupo`)
    REFERENCES `proyecto2`.`categoria_grupo` (`idCategoria_Grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`bitacoraporequipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`bitacoraporequipo` (
  `idbitacoraPorEquipo` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `pj` INT(11) NULL DEFAULT NULL COMMENT '',
  `pg` INT(11) NULL DEFAULT NULL COMMENT '',
  `pe` INT(11) NULL DEFAULT NULL COMMENT '',
  `pp` INT(11) NULL DEFAULT NULL COMMENT '',
  `GF` INT(11) NULL DEFAULT NULL COMMENT '',
  `gc` INT(11) NULL DEFAULT NULL COMMENT '',
  `grupo_idgrupo` INT(11) NOT NULL COMMENT '',
  `equipo_idequipo` INT(11) NOT NULL COMMENT '',
  `Fecha_Creacion` DATE NULL DEFAULT NULL COMMENT '',
  `Fecha_Edicion` DATE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idbitacoraPorEquipo`)  COMMENT '',
  INDEX `fk_bitacoraPorEquipo_grupo1_idx` (`grupo_idgrupo` ASC)  COMMENT '',
  INDEX `fk_bitacoraPorEquipo_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  CONSTRAINT `fk_bitacoraPorEquipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bitacoraPorEquipo_grupo1`
    FOREIGN KEY (`grupo_idgrupo`)
    REFERENCES `proyecto2`.`grupo` (`idgrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`evento_has_confederaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`evento_has_confederaciones` (
  `Evento_idEvento` INT(11) NOT NULL COMMENT '',
  `confederaciones_idconfederaciones` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`Evento_idEvento`, `confederaciones_idconfederaciones`)  COMMENT '',
  INDEX `fk_Evento_has_confederaciones_confederaciones1_idx` (`confederaciones_idconfederaciones` ASC)  COMMENT '',
  INDEX `fk_Evento_has_confederaciones_Evento_idx` (`Evento_idEvento` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_has_confederaciones_Evento`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_confederaciones_confederaciones1`
    FOREIGN KEY (`confederaciones_idconfederaciones`)
    REFERENCES `proyecto2`.`confederaciones` (`idconfederaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`evento_has_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`evento_has_equipo` (
  `Evento_idEvento` INT(11) NOT NULL COMMENT '',
  `equipo_idequipo` INT(11) NOT NULL COMMENT '',
  `ganador` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `segundo_lugar` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`Evento_idEvento`, `equipo_idequipo`)  COMMENT '',
  INDEX `fk_Evento_has_equipo_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  INDEX `fk_Evento_has_equipo_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_has_equipo_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_equipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `proyecto2`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto2`.`sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto2`.`sede` (
  `Evento_idEvento` INT(11) NOT NULL COMMENT '',
  `Pais_idPais` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`Evento_idEvento`, `Pais_idPais`)  COMMENT '',
  INDEX `fk_Evento_has_Pais_Pais1_idx` (`Pais_idPais` ASC)  COMMENT '',
  INDEX `fk_Evento_has_Pais_Evento1_idx` (`Evento_idEvento` ASC)  COMMENT '',
  CONSTRAINT `fk_Evento_has_Pais_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `proyecto2`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Pais_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `proyecto2`.`pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `proyecto2` ;

-- -----------------------------------------------------
-- procedure Insert_Evento_has_Confederaciones
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Insert_Evento_has_Confederaciones`( PEvento_idEvento INT(11), PConfederaciones_idconfederaciones INT(11))
BEGIN
INSERT INTO proyecto2.evento_has_confederaciones
(
  Evento_idEvento
 ,confederaciones_idconfederaciones
)
VALUES
(
  PEvento_idEvento -- Evento_idEvento - INT(11) NOT NULL
 ,PConfederaciones_idconfederaciones -- confederaciones_idconfederaciones - INT(11) NOT NULL
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Insert_Evento_has_Equipo
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Insert_Evento_has_Equipo`(PEvento_idEvento INT(11), PEquipo_idequipo INT(11))
BEGIN
INSERT INTO proyecto2.evento_has_equipo
(
  Evento_idEvento
 ,equipo_idequipo
 ,ganador
 ,segundo_lugar
)
VALUES
(
  PEvento_idEvento -- Evento_idEvento - INT(11) NOT NULL
 ,PEvento_idEvento -- equipo_idequipo - INT(11) NOT NULL
 ,0 -- ganador - TINYINT(1)
 ,0 -- segundo lugar - TINYINT(1)
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure Insert_sede
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Insert_sede`(IN PEvento_idEvento INT(11), IN PPais_idPais INT(11))
BEGIN
INSERT INTO proyecto2.sede
(
  Evento_idEvento
 ,Pais_idPais
)
VALUES
(
  PEvento_idEvento -- Evento_idEvento - INT(11) NOT NULL
 ,PPais_idPais -- Pais_idPais - INT(11) NOT NULL
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_accion
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_accion`(pidJugador int, pidPartido int, ptiempo int, pCatalogoAcciones int)
BEGIN
insert into accion(
	jugador_idjugador,
    partido_idpartido,
    tiempo,
    CatalogodeAcciones_idCatalogodeAcciones
  )
values(
	pidJugador,
    pidPartido,
    ptiempo,
    pCatalogoAcciones
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_administrador
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_administrador`(pUsername varchar(45), pPassword varchar(45))
BEGIN
	insert into proyecto2.administrador(username, password)
    values(pUsername, AES_ENCRYPT(pPassword, 'basesrulez'));
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_alineacion
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_alineacion`(idEquipo int)
BEGIN
insert into alineacion( equipo_idequipo)
values( idEquipo);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_bitacoraporEquipo
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_bitacoraporEquipo`(idEquipo int, idGrupo int)
BEGIN
INSERT INTO `proyecto2`.`bitacoraporequipo`
(
`pj`,
`pg`,
`pe`,
`pp`,
`GF`,
`gc`,
`grupo_idgrupo`,
`equipo_idequipo`)
VALUES
(
0,
0,
0,
0,
0,
0,
idGrupo,
idEquipo);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_catalogo_de_acciones
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_catalogo_de_acciones`(pNombre varchar(45))
BEGIN
	insert into proyecto2.catalogo_de_acciones(nombre)
    values(pNombre);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_categoria_grupo
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_categoria_grupo`(pNombre varchar(45))
BEGIN
	insert into proyecto2.categoria_grupo(nombre)
    values(pNombre);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_confederacion
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_confederacion`(pNombre varchar(45), pIcono blob)
BEGIN
	insert into proyecto2.confederaciones(nombre, icono)
    values(pNombre, pIcono);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_continente
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_continente`(pNombre varchar(45))
BEGIN
	insert into proyecto2.continente(nombre)
    values(pNombre);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_equipo
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_equipo`(pnombre varchar(45), pbandera blob, ptecnico varchar(95), pconfederaciones int, pPais int)
BEGIN
	insert into equipo(
    nombre,
    bandera,
    tecnico,
    confederaciones_idconfederaciones,
    Pais_idPais
    )
    values(
    pnombre,
    pbandera ,
    ptecnico ,
    pconfederaciones ,
    pPais 
    );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_estadio
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_estadio`(pnombre varchar(45), idPais int, pcapacidad int)
BEGIN
insert into estadio(
	nombre,
	Pais_idPais,
	capacidad
)
values(
	pnombre,
    idPais,
    pcapacidad
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_evento
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_evento`(pNombre varchar(45), pFechaInicio date, cantidad int, pTipoEvento int)
BEGIN
insert into evento(
	nombre,
	fecha_inicio,
    cantidad_equipos,
	Tipo_Eventos_idTipo_Eventos
)


values(
	pNombre ,
	pFechaInicio ,
    cantidad,
	pTipoEvento
);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_grupo
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_grupo`(pEventID int, pNombre varchar(45), categoria int)
BEGIN
	insert into proyecto2.grupo(Evento_idEvento, nombre, Categoria_Grupo_idCategoria_Grupo)
    values(pEventID, pNombre, categoria);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_jugador
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_jugador`(pnumCamiseta int, pnombre varchar(45), pApellidos varchar(45), pCedula varchar(45), pfoto blob,
idEquipo int, pPais int, pPosicion int )
BEGIN
	insert into jugador(
    numeroCamiseta,
    nombre,
    apellidos,
    cedula,
    foto,
    equipo_idequipo,
    suspendido,
    alineacion_idalineacion,
    Pais_idPais,
    capitan,
    posicion_idposicion
    )
    values (
    pnumCamiseta ,
    pnombre ,
    pApellidos ,
    pCedula ,
    pfoto ,
	idEquipo ,
	0 ,
    null ,
    pPais,
    0,
    pPosicion
    );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_pais
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_pais`(pNombre varchar(45), pBandera blob, pContinenteID int)
BEGIN
	insert into proyecto2.pais(nombre, bandera, Continente_idContinente)
    values(pNombre, pBandera, pContinente);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_partido
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_partido`(pEventID int, pEquipoLocal int, pEquipoVisita int,
									pEstadio int, pFecha date)
BEGIN
	insert into partido(Evento_idEvento, EquipoLocal, EquipoVisita, Ganador,
    estadio_idestadio, fecha)
    values(pEventID , pEquipoLocal , pEquipoVisita , 0 ,
									pEstadio , pFecha );
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_posicion
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_posicion`(pNombre varchar(45))
BEGIN
	insert into posicion(nombre)
    values(pNombre);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insert_tipo_evento
-- -----------------------------------------------------

DELIMITER $$
USE `proyecto2`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `insert_tipo_evento`(pNombre varchar(45))
BEGIN
	insert into tipo_eventos(nombre)
    values(pNombre);
END$$

DELIMITER ;
USE `proyecto2`;

DELIMITER $$
USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`catalogo_edit`
BEFORE UPDATE ON `proyecto2`.`catalogo_de_acciones`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`catalogo_timestamp`
BEFORE INSERT ON `proyecto2`.`catalogo_de_acciones`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`continentes_edit`
BEFORE UPDATE ON `proyecto2`.`continente`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`continentes_timestamp`
BEFORE INSERT ON `proyecto2`.`continente`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`pais_edit`
BEFORE UPDATE ON `proyecto2`.`pais`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`pais_timestamp`
BEFORE INSERT ON `proyecto2`.`pais`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`confederaciones`
BEFORE UPDATE ON `proyecto2`.`confederaciones`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`confederaciones_timestamp`
BEFORE INSERT ON `proyecto2`.`confederaciones`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`equipo_edit`
BEFORE UPDATE ON `proyecto2`.`equipo`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`equipo_timestamp`
BEFORE INSERT ON `proyecto2`.`equipo`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`alineaciones_edit`
BEFORE UPDATE ON `proyecto2`.`alineacion`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`alineaciones_timestamp`
BEFORE INSERT ON `proyecto2`.`alineacion`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`posicion_timestamp`
BEFORE INSERT ON `proyecto2`.`posicion`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`posicion_edit`
BEFORE UPDATE ON `proyecto2`.`posicion`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`jugador_edit`
BEFORE UPDATE ON `proyecto2`.`jugador`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`jugador_timestamp`
BEFORE INSERT ON `proyecto2`.`jugador`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`tipo_timestamp`
BEFORE INSERT ON `proyecto2`.`tipo_eventos`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`tipo_edit`
BEFORE UPDATE ON `proyecto2`.`tipo_eventos`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`evento_timestamp`
BEFORE INSERT ON `proyecto2`.`evento`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`event_edit`
BEFORE UPDATE ON `proyecto2`.`evento`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`estadio_edit`
BEFORE UPDATE ON `proyecto2`.`estadio`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`estadio_timestamp`
BEFORE INSERT ON `proyecto2`.`estadio`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`partido_edit`
BEFORE UPDATE ON `proyecto2`.`partido`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`partido_timestamp`
BEFORE INSERT ON `proyecto2`.`partido`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`accion_edit`
BEFORE UPDATE ON `proyecto2`.`accion`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`accion_timestamp`
BEFORE INSERT ON `proyecto2`.`accion`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`bitacora_edit`
BEFORE UPDATE ON `proyecto2`.`bitacora`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`bitacora_timestamp`
BEFORE INSERT ON `proyecto2`.`bitacora`
FOR EACH ROW
SET NEW.fecha_creacion = CURRENT_TIMESTAMP$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`categoria_edit`
BEFORE UPDATE ON `proyecto2`.`categoria_grupo`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`categoria_timestamp`
BEFORE INSERT ON `proyecto2`.`categoria_grupo`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`grupo_edit`
BEFORE UPDATE ON `proyecto2`.`grupo`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`grupo_timestamp`
BEFORE INSERT ON `proyecto2`.`grupo`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`bitacoraporequipo_edit`
BEFORE UPDATE ON `proyecto2`.`bitacoraporequipo`
FOR EACH ROW
SET NEW.fecha_edicion = NOW()$$

USE `proyecto2`$$
CREATE
DEFINER=`proyecto2`@`localhost`
TRIGGER `proyecto2`.`bitacoraporequipo_timestamp`
BEFORE INSERT ON `proyecto2`.`bitacoraporequipo`
FOR EACH ROW
SET NEW.fecha_creacion = NOW()$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
